#!/usr/bin/env bash

# Exit on error
set -e

# VARS
export ENVIRONMENT=dev
export WORKSPACE_PATH=~/workspace
export SCRIPT_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
export APP_NAME=face-web
export APP_OWNER=austin-dsc
export APP_PATH=$WORKSPACE_PATH/$APP_NAME
export APP_REPO=https://github.com/$APP_OWNER/$APP_NAME.git
export DEV_BRANCH=accordion-store

# Logging stuff.
function e_header()   { echo -e "\n\033[1m$@\033[0m"; }
function e_success()  { echo -e " \033[1;32m✔\033[0m  $@"; }
function e_error()    { echo -e " \033[1;31m✖\033[0m  $@"; }
function e_arrow()    { echo -e " \033[1;34m➜\033[0m  $@"; }
function throw_error() { e_error $@; exit 1;}

# Update the app repo
function update_app() {
  e_header "Updating $APP_NAME."
  if [ -d $APP_PATH ]; then
    e_arrow "in $APP_PATH"
    cd $APP_PATH
    git pull -q
    e_arrow "switching to $DEV_BRANCH branch."
    git checkout $DEV_BRANCH -q
    cd $SCRIPT_PATH
    e_success "done."
  else
    throw_error "$APP_PATH does not exist."
  fi
}

# Clone app repo into app path
function clone_app() {
  if [ -d $APP_PATH ]; then
    e_header "App already exists."
    update_app
  else
    e_header "cloning $APP_NAME ($APP_REPO)"
    e_arrow "into $APP_PATH"
    git clone $APP_REPO $APP_PATH -q
    e_arrow "switching to $DEV_BRANCH branch."
    git checkout $DEV_BRANCH -q
    if [ -d $APP_PATH ]; then
      e_success "done."
    else
      throw_error "Clone failed and $APP_PATH was not created."
    fi
  fi
}

function install_ember_cli() {
  if [[ ! "$(type -P ember)" ]]; then
    e_header "Installing the ember-cli npm global dependency."
    npm install -g ember-cli --silent
    e_success "done."
  else
    e_header "Updating the ember-cli npm package."
    npm update ember-cli --silent
    e_success "done."
  fi
}

function install_app_packages() {
  if [ -d $APP_PATH ]; then
    e_header "Installing $APP_NAME local npm dependencies."
    cd $APP_PATH
    npm install --silent
    cd $SCRIPT_PATH
    e_success "done."
  else
    throw_error "$APP_PATH does not exist."
  fi
}

function run() {
  e_header "Setting up $APP_NAME ($ENVIRONMENT)"
  clone_app
  install_ember_cli
  install_app_packages
}

run
