#!/usr/bin/env bash
# Logging stuff.
function e_header()   { echo -e "\n\033[1m$@\033[0m"; }
function e_success()  { echo -e " \033[1;32m✔\033[0m  $@"; }
function e_error()    { echo -e " \033[1;31m✖\033[0m  $@"; }
function e_arrow()    { echo -e " \033[1;34m➜\033[0m  $@"; }

# VARS
export ENVIRONMENT=dev
export WORKSPACE_PATH=~/workspace
export SCRIPT_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
export APP_NAME=face-web
export APP_OWNER=austin-dsc
export APP_PATH=$WORKSPACE_PATH/$APP_NAME
export APP_REPO=https://github.com/$APP_OWNER/$APP_NAME.git

# Update the app repo
function upated_app() {
  e_header "Updating $APP_NAME"
  if [ -d $APP_PATH ]; then
    cd $APP_PATH
    git checkout master && git pull origin master --rebase
  else
    e_error "$APP_PATH does not exist."
  fi
}

# Clone app repo into app path
function clone_app() {
	if [ -d $APP_PATH ]; then
    e_header "$APP_PATH already exists."
    update_app()
  else
    e_header "cloning $APP_NAME ($APP_REPO)"
    e_arrow "into $APP_PATH"

    git clone $APP_REPO $APP_PATH -q
    if [ -d $APP_PATH ]; then
      e_success "done."
    else
      e_error "Clone failed and $APP_PATH was not created."
    fi
  fi
}

function run() {
  e_header "Setup $APP_NAME - $ENVIRONMENT"
  clone_app
}

run
